<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INBANGNBLENO10" name="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest" tests="22" failures="3" timestamp="23 Oct 2018 20:35:24 GMT" time="186.395" errors="0">
  <testcase name="test09_Th100Ex0Scanned10Known" time="8.167" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test01_Th0Ex0ScannedAllUnknown" time="9.356" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest">
    <failure type="java.lang.AssertionError" message="Failed: Threshold met status expected:&lt;true&gt; but was:&lt;false&gt;">
      <![CDATA[java.lang.AssertionError: Failed: Threshold met status expected:<true> but was:<false>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:185)
at com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest.test01_Th0Ex0ScannedAllUnknown(ThCalculationFCCWhenThNotMetTest.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test01_Th0Ex0ScannedAllUnknown -->
  <testcase name="test04_Th0Ex10Scanned10Known" time="9.419" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test17_Th20Ex10Scanned10Unknown10Known" time="9.189" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test05_Th0Ex10Scanned8Known" time="10.500" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test11_Th100Ex10Scanned10Known" time="7.452" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test19_Th20Ex10Scanned8KnownEqualsThreshold" time="7.597" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test20_Th20Ex8Scanned10Known2Extra" time="8.369" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest">
    <failure type="java.lang.AssertionError" message="Failed: Sending message or No Pedning cc to accept/reject or already accepted">
      <![CDATA[java.lang.AssertionError: Failed: Sending message or No Pedning cc to accept/reject or already accepted
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
at com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest.test20_Th20Ex8Scanned10Known2Extra(ThCalculationFCCWhenThNotMetTest.java:165)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test20_Th20Ex8Scanned10Known2Extra -->
  <testcase name="test06_Th0Ex8Scanned10Known" time="9.796" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test07_Th0Ex10Scanned9KnownWithMissingAndExtra" time="8.544" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test08_Th100Ex0ScannedAllUnknown" time="7.723" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test18_Th20Ex10Scanned10Known" time="7.333" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test21_Th20Ex10Scanned9Known2Missing1Extra" time="7.490" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test12_Th100Ex10Scanned8Known" time="7.592" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test22_Th20Ex9Scanned7Known2Missing" time="7.774" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest">
    <failure type="java.lang.AssertionError" message="Failed: Sending message or No Pedning cc to accept/reject or already accepted">
      <![CDATA[java.lang.AssertionError: Failed: Sending message or No Pedning cc to accept/reject or already accepted
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
at com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest.test22_Th20Ex9Scanned7Known2Missing(ThCalculationFCCWhenThNotMetTest.java:179)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test22_Th20Ex9Scanned7Known2Missing -->
  <testcase name="test02_Th0Ex0Scanned10Known" time="10.415" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test10_Th100Ex10Scanned10Unknown10Known" time="8.310" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test16_Th20Ex0Scanned10Known" time="7.611" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test15_Th20Ex0ScannedAllUnknown" time="7.478" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test13_Th100Ex8Scanned10Known" time="8.555" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test03_Th0Ex10Scanned10Unknown10Known" time="10.006" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
  <testcase name="test14_Th100Ex10Scanned9KnownWithMissingAndExtra" time="7.719" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest"/>
</testsuite> <!-- com.oatsystems.test.mv.ccthreshold.ThCalculationFCCWhenThNotMetTest -->
