<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INBANGNBLENO10" name="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest" tests="22" failures="3" timestamp="23 Oct 2018 20:35:24 GMT" time="210.029" errors="0">
  <testcase name="test17_Th20Ex10Scanned10Unknown10Known" time="9.999" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test16_Th20Ex0Scanned10Known" time="10.795" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test05_Th0Ex10Scanned8Known" time="9.077" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test11_Th100Ex10Scanned10Known" time="9.191" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test13_Th100Ex8Scanned10Known" time="9.179" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test06_Th0Ex8Scanned10Known" time="9.814" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test19_Th20Ex10Scanned8KnownEqualsThreshold" time="10.011" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test14_Th100Ex10Scanned9KnownWithMissingAndExtra" time="9.135" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test03_Th0Ex10Scanned10Unknown10Known" time="9.365" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test07_Th0Ex10Scanned9KnownWithMissingAndExtra" time="8.571" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test04_Th0Ex10Scanned10Known" time="9.305" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test09_Th100Ex0Scanned10Known" time="10.471" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test01_Th0Ex0ScannedAllUnknown" time="9.899" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest">
    <failure type="java.lang.AssertionError" message="Failed: Threshold met status expected:&lt;true&gt; but was:&lt;false&gt;">
      <![CDATA[java.lang.AssertionError: Failed: Threshold met status expected:<true> but was:<false>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:185)
at com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest.test01_Th0Ex0ScannedAllUnknown(ThCalculationFCCAlwaysTest.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test01_Th0Ex0ScannedAllUnknown -->
  <testcase name="test08_Th100Ex0ScannedAllUnknown" time="9.122" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test02_Th0Ex0Scanned10Known" time="10.078" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test20_Th20Ex8Scanned10Known2Extra" time="9.020" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest">
    <failure type="java.lang.AssertionError" message="Failed: Threshold met status expected:&lt;false&gt; but was:&lt;true&gt;">
      <![CDATA[java.lang.AssertionError: Failed: Threshold met status expected:<false> but was:<true>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:185)
at com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest.test20_Th20Ex8Scanned10Known2Extra(ThCalculationFCCAlwaysTest.java:166)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test20_Th20Ex8Scanned10Known2Extra -->
  <testcase name="test21_Th20Ex10Scanned9Known2Missing1Extra" time="9.748" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test10_Th100Ex10Scanned10Unknown10Known" time="9.429" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test18_Th20Ex10Scanned10Known" time="8.994" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test22_Th20Ex9Scanned7Known2Missing" time="9.774" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest">
    <failure type="java.lang.AssertionError" message="Failed: Threshold met status expected:&lt;false&gt; but was:&lt;true&gt;">
      <![CDATA[java.lang.AssertionError: Failed: Threshold met status expected:<false> but was:<true>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:185)
at com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest.test22_Th20Ex9Scanned7Known2Missing(ThCalculationFCCAlwaysTest.java:180)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test22_Th20Ex9Scanned7Known2Missing -->
  <testcase name="test12_Th100Ex10Scanned8Known" time="9.921" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
  <testcase name="test15_Th20Ex0ScannedAllUnknown" time="9.131" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest"/>
</testsuite> <!-- com.oatsystems.test.mv.ccthreshold.ThCalculationFCCAlwaysTest -->
