<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INBANGNBLENO10" name="com.chkpoint.jaytest1.Inventory_Test_UnknownValid" tests="4" failures="0" timestamp="31 Oct 2018 04:46:50 GMT" time="180.646" errors="0">
  <testcase name="Test01ReceiveRetireThenCycleCountAtSameLocation" time="44.101" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownValid"/>
  <testcase name="Test04ReceiveRetireThenRetireAtSameLocation" time="47.878" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownValid"/>
  <testcase name="Test02ReceiveRetireThenPutawayAtSameLocation" time="44.062" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownValid"/>
  <testcase name="Test03ReceiveRetireThenReturnAtSameLocation" time="44.605" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownValid"/>
</testsuite> <!-- com.chkpoint.jaytest1.Inventory_Test_UnknownValid -->
